# Generated by Django 4.2.1 on 2023-11-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='ai',
            field=models.BooleanField(default=False),
        ),
    ]
